" simpler syntax highlighting
hi link haskellBottom      NONE
hi link haskellIdentifier  NONE
hi link haskellType        NONE
hi link haskellQuotedType  NONE
hi link haskellSeparator   NONE
hi link haskellDelimiter   NONE
hi link haskellImportBlock NONE
hi link haskellDefault     Structure
hi link haskellWhere       Structure
