#!/usr/bin/env sh

# Enable yabai. For this to work, must do the following after each `brew upgrade`:
# - `sudo visudo -f /private/etc/sudoers.d/yabai`
# - replace the hash with the output of `shasum -a 256 $(which yabai)`
# <https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)>
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa

# Any yabai config goes here. However, I'm only using yabai's command interface,
# not tiling by default, so the default config is fine.
# <https://github.com/koekeishiya/yabai/wiki/Configuration>

echo "yabai enabled."
