;; -*- mode: emacs-lisp -*-
;;
;; This file is loaded by Spacemacs at startup.
;; Use <SPC f e R> to reload after changing.
;; 
;; The original template is here:
;; https://github.com/syl20bnr/spacemacs/blob/master/core/templates/.spacemacs.template

(let ((default-directory (file-name-directory load-file-name)))

  ;; Load the configuration functions called by Spacemacs during initialization.
  ;; The load order reflects the order that Spacemacs will invoke them.
  (load (expand-file-name "core-init.el"))
  (load (expand-file-name "user-init.el"))
  (load (expand-file-name "layers.el"))
  (load (expand-file-name "user-config.el"))

  ;; Use a separate file for customizations generated by Emacs.
  (setq custom-file (expand-file-name "custom.el"))
  (load custom-file))
