;;;; Packages

;; Turn on the built-in package manager, add package repos.
(require 'package)
(add-to-list 'package-archives '("melpa" . "https://melpa.org/packages/") t)
(package-initialize)

;; Bootstrap the better package manager.
(unless (package-installed-p 'use-package)
  (package-refresh-contents)
  (package-install 'use-package))
(require 'use-package)
(setq use-package-always-ensure t)

;; Install and configure packages that affect global behavior.
(load (concat user-emacs-directory "init/global"))

;; Install and configure frameworks used by mode-specific packages.
(load (concat user-emacs-directory "init/company"))
(load (concat user-emacs-directory "init/flycheck"))

;; Install and configure specific modes.
(load (concat user-emacs-directory "init/org"))
(load (concat user-emacs-directory "init/haskell"))


;;;; Theme

;; A nice light theme with good org-mode support.
(use-package leuven-theme
  :config
    (load-theme 'leuven t))


;;;; Settings


;;; File handling

;; Use UTF-8 and unix line endings by default.
(prefer-coding-system 'utf-8-unix)

;; Automatically follow symlinks.
(setq vc-follow-symlinks t)

;; Better buffer name disambiguation.
(require 'uniquify)
(setq uniquify-buffer-name-style 'forward)

;; Don't litter my file system with back-up files.
(setq backup-directory-alist `(("." . ,(concat user-emacs-directory "backup"))))
(setq backup-by-copying t)


;;; Behaviors

;; Disable "smart" indenting.
(setq-default electric-indent-inhibit t)

;; Only a single space to end sentences.
(setq sentence-end-double-space nil)


;;; User interface

;; Don't show startup screen.
(setq inhibit-startup-screen t)

;; Show column number in mode line.
(setq column-number-mode t)

;; Highlight matching parens.
(show-paren-mode 1)
(setq show-paren-delay 0)


;;; GUI-specific

;; Use a temp file for stuff generated by the GUI customizer.
(setq custom-file (make-temp-file "emacs-custom.el"))

;; Maximize window by default.
(add-to-list 'default-frame-alist '(fullscreen . maximized))

;; Disable tool bar and scroll bars.
(tool-bar-mode -1)
(scroll-bar-mode -1)

;; Turn off mouse highlighting.
;; (setq mouse-highlight nil)
